name: Deploy

on:
  merge:
    branches:
      - production

jobs:
  deploy:
    name: Deploy my app

    # IMPORTANT: the workflow must have write access to deployments, otherwise the action will fail.
    permissions:
      deployments: write

    evn:
      ENV_URL: https://d2zddj4dy0ay4b.cloudfront.net/

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: ${{ ENV_URL }}
          environment: production

      - name: Deploy my app
        run: |
          aws s3 sync --delete build/client/ ${{ secrets.BUCKET }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ ENV_URL }}
          state: 'success'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ ENV_URL }}
          state: 'failure'
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}